[package]
name = "contour-cli"
version = "0.1.0"
authors = ["Owen Campbell <ocampbell95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contour = { path = "../contour" }
clap ="3.0.0-beta.2"
